"""Change previous_tests to JSON.

Revision ID: 16e578626d45
Revises: 2cbf5c81b941
Create Date: 2025-11-24 18:57:39.076586

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '16e578626d45'
down_revision: Union[str, Sequence[str], None] = '2cbf5c81b941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.alter_column(
            'previous_tests',
            existing_type=sa.TEXT(),
            type_=sa.JSON(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.alter_column(
            'previous_tests',
            existing_type=sa.JSON(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
